name: Bats Tests

on:
  push:
    branches:
      - main
      - develop
    tags:
      - 'v*'
  pull_request:
    branches:
      - main
      - develop
    

jobs:
  test-ids:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        if [[ "${{ matrix.os }}" == "ubuntu-latest" ]]; then
          sudo apt-get update
          sudo apt-get install -y bats curl jq sed
        elif [[ "${{ matrix.os }}" == "macos-latest" ]]; then
          brew install bats coreutils curl jq gnu-sed docker
        fi

    - name: Install Wazuh agent
      run: |
        curl -sfL https://raw.githubusercontent.com/adorsys-gis/wazuh-agent/main/scripts/install.sh | sudo WAZUH_MANAGER=127.0.0.1 bash

    - name: Make script executable
      run: chmod +x ./scripts/install.sh
      
    - name: Install Suricata
      run: |
        sudo ./scripts/install.sh

    - name: Run Bats tests
      run: sudo bats tests/

  test-ips:
    runs-on: ubuntu-latest
    needs: test-ids

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y bats curl jq sed

    - name: Install Wazuh agent
      run: |
        curl -sfL https://raw.githubusercontent.com/adorsys-gis/wazuh-agent/main/scripts/install.sh | sudo WAZUH_MANAGER=127.0.0.1 bash

    - name: Make script executable
      run: chmod +x ./scripts/install.sh

    - name: Install Suricata in IPS mode
      run: |
        sudo ./scripts/install.sh --mode ips

    - name: Run Bats tests for IPS mode
      run: sudo MODE=ips bats tests/

  release:
    name: Release
    permissions: write-all
    runs-on: ubuntu-latest
    needs: test-ips
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        if: startsWith(github.ref, 'refs/tags/v')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.get_version.outputs.VERSION }}
          release_name: Release ${{ steps.get_version.outputs.VERSION }}
          draft: false
          prerelease: false